### PR TITLE
Suppress wrong broadcasting over x in broadcasteval()

### PR DESCRIPTION
**Pull request by wsshin**
Fixes https://github.com/JuliaApproximation/ApproxFun.jl/issues/762.

### CODE REVIEW

**Comment by wsshin** [comment]
Wanted to add unit tests verifying this fix, but I am not sure how to create a simple one within `ApproxFunBase` (without `using ApporxFun`).  If anyone has a good idea, please advise.

**Comment by dlfivefifty** [comment]
Yes the unit tests is an issue with how the code is split apart

**Comment by jishnub** [comment]
@wsshin It should be possible to add a test like this in `ApproxFunBase`, which covers the line changed:
```julia
f = Fun(PointSpace(1:3), 1:3)
g = f.^2
@test g.(points(f)) == f.(points(f)).^2
```
Another test that covers the actual issue may be added to `ApproxFunOrthogonalPolynomials`. Given that we test against downstream packages, it should prevent regression.

**Comment by jishnub** [comment]
Looks good to merge. Further tests may be added to `ApproxFunOrthogonalPolynomials`

**Pull request merged**
