### PR TITLE
Fix kron product on sum spaces

### PR DESCRIPTION
**Pull request by mzaffalon**
Fix JuliaApproximation/ApproxFun.jl#929.

### CODE REVIEW

**Comment by jishnub** [comment]
Thanks! Could you also bump the patch version?

**Comment by mzaffalon** [comment]
You mean Project.toml`?

**Comment by mzaffalon** [comment]
Thank you!

Would you merge also https://github.com/JuliaApproximation/ApproxFunFourier.jl/pull/117 or would you like more tests?

**Comment by jishnub** [comment]
I think that's fine. I'll merge that after backporting this to the v0.8 branch.

**Pull request merged**
