### PR TITLE
=== in comparing with nothing

### PR DESCRIPTION
**Pull request by jishnub**
This might help with type-inference on older versions of Julia

### CODE REVIEW

**Comment by dlfivefifty** [comment]
I would suggest just using `isnothing(xst)`

**Comment by jishnub** [comment]
`isnothing(x)` is equivalent to `x === nothing` on recent Julia versions, but from what I remember, the `=== nothing` used to be the recommended style on older versions. I can't remember if they are equivalent on v1.6, so I went with the one that is known to be better on old versions.

**Comment by dlfivefifty** [comment]
If `isnothing` isn't the recommended style then its weird the function even exists...

**Comment by jishnub** [comment]
I think the idea was that custom `Nothing` types may extend `isnothing` for their types, which wouldn't be possible with `=== nothing`. However, the performance issue was unfortunate, which is why it was recommended to use `=== nothing` if not working with custom types. At least on recent Julia versions, all of `isnothing`, `=== nothing` and `== nothing` are equivalent, so that's one less thing to remember.

**Pull request merged**
